version: "3"

services:

  coda_srv:
    image: coda_img
    container_name: coda_cont
    network_mode: host
    build:
      # set the build context to the directory containing build files
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    environment:
      # pass the display variable to the container
      - DISPLAY=${DISPLAY}
      # enable NVIDIA GPU access inside the container
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      # disable qt-X11 memory sharing for RViz
      # - QT_X11_NO_MITSHM=1
      # - ROS_IP=192.168.131.113
      # - ROS_MASTER_URI=http://192.168.131.1:11311
      - PC_TOPIC=/philbart/lidar_points

    entrypoint: /coda_entrypoint.sh
    